#
# Common widget acompressor (FFmpeg dynamic range compressor)
#
# Usage:
#   Object.Widget.acompressor."N" {
#       index     1
#       no_pm     "true"
#   }
#
# UUID: d4464a1b-7be5-4059-c1ba-91807f6e5d43

Class.Widget."acompressor" {
	DefineAttribute."index" {}
	DefineAttribute."instance" {}

	<include/components/widget-common.conf>

	DefineAttribute."cpc" {
		token_ref	"comp.word"
	}

	attributes {
		!constructor [
			"index"
			"instance"
		]

		!mandatory [
			"no_pm"
			"uuid"
		]

		!immutable [
			"uuid"
			"type"
		]

		!deprecated [
			"preload_count"
		]

		unique	"instance"
	}

	num_input_audio_formats 4
	num_output_audio_formats 4

	Object.Base.input_audio_format [
		# S16 stereo 48 kHz
		{
			in_rate			48000
			in_bit_depth		16
			in_valid_bit_depth	16
		}
		# S32 stereo 48 kHz
		{
			in_rate			48000
			in_bit_depth		32
			in_valid_bit_depth	32
		}
		# S16 stereo 16 kHz
		{
			in_rate			16000
			in_bit_depth		16
			in_valid_bit_depth	16
		}
		# S32 stereo 16 kHz
		{
			in_rate			16000
			in_bit_depth		32
			in_valid_bit_depth	32
		}
	]

	Object.Base.output_audio_format [
		{
			out_rate		48000
			out_bit_depth		16
			out_valid_bit_depth	16
		}
		{
			out_rate		48000
			out_bit_depth		32
			out_valid_bit_depth	32
		}
		{
			out_rate		16000
			out_bit_depth		16
			out_valid_bit_depth	16
		}
		{
			out_rate		16000
			out_bit_depth		32
			out_valid_bit_depth	32
		}
	]

	# UUID: d4464a1b-7be5-4059-c1ba-91807f6e5d43
	uuid		"1b:4a:46:d4:e5:7b:59:40:c1:ba:91:80:7f:6e:5d:43"
	type		"effect"
	no_pm		"true"
	cpc		3000
	num_input_pins		1
	num_output_pins		1
}
