#
# A microWakeWord keyword-spotting component for SOF. All attributes defined
# herein are namespaced by alsatplg to "Object.Widget.mww.attribute_name"
#

Class.Widget."mww" {
	#
	# Pipeline ID
	#
	DefineAttribute."index" {
		type "integer"
	}

	#
	# Unique instance for MWW widget
	#
	DefineAttribute."instance" {
		type "integer"
	}

	# Include common widget attributes definition
	<include/components/widget-common.conf>

	attributes {
		!constructor [
			"index"
			"instance"
		]
		!mandatory [
			"num_input_pins"
			"num_output_pins"
			"num_input_audio_formats"
			"num_output_audio_formats"
		]

		!immutable [
			"uuid"
		]
		!deprecated [
			"preload_count"
		]
		unique	"instance"
	}

	#
	# Default attributes for mww
	# UUID: 4067fe1d-cd63-4877-966b-a06ded1719ce
	#
	uuid			"1d:fe:67:40:63:cd:77:48:96:6b:a0:6d:ed:17:19:ce"
	type			"effect"
	no_pm			"true"
	num_input_pins		1
	num_output_pins		1
}
