# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright (c) 2026 Intel Corporation. All rights reserved.
#
# Steam Audio processing component
#
# All attributes defined herein are namespaced by alsatplg to
# "Object.Widget.steamaudio.N.attribute_name"
#
# Usage: this component can be used by declaring in the parent object. i.e.
#
# Object.Widget.steamaudio."N" {
#     index 1
# }
#
# Where index is the pipeline ID and N is a unique integer in the parent object.

<include/controls/mixer.conf>
<include/controls/bytes.conf>

Define {
	STEAMAUDIO_UUID "61:65:74:53:61:6d:64:75:69:6f:73:74:65:61:6d:31"
	STEAMAUDIO_CPC 100000
}

Class.Widget."steamaudio" {
	#
	# Pipeline ID
	#
	DefineAttribute."index" {
		type "integer"
	}

	#
	# Unique instance for steamaudio widget
	#
	DefineAttribute."instance" {
		type "integer"
	}

	# Include common widget attributes definition
	<include/components/widget-common.conf>

	DefineAttribute."cpc" {
		token_ref "comp.word"
	}

	DefineAttribute."is_pages" {
		token_ref "comp.word"
	}

	#
	# Steam Audio controls: Master Volume, Master Switch, Runtime Configuration Bytes
	#
	Object.Control {
		mixer."1" {
			name "SteamAudio Playback Volume"
			Object.Base.channel.1 {
				name "fl"
				shift 0
			}
			Object.Base.channel.2 {
				name "fr"
			}
			Object.Base.ops.1 {
				name "ctl"
				info "volsw"
				get 256
				put 256
			}
			max 45
			Object.Base.tlv.1 {
				name "vtlv_m90s2"
				Object.Base.scale.1 {
					name m90s2
					min -9000
					step 200
					mute 1
				}
			}
		}

		mixer."2" {
			name "SteamAudio Playback Switch"
			Object.Base.channel.1 {
				name "fc"
				shift 0
			}
			Object.Base.ops.1 {
				name "ctl"
				info "volsw"
				get 259
				put 259
			}
			max 1
		}

		bytes."1" {
			name "SteamAudio Config"
			max 4096
		}
	}

	attributes {
		!constructor [
			"index"
			"instance"
		]
		!mandatory [
			"num_input_pins"
			"num_output_pins"
			"num_input_audio_formats"
			"num_output_audio_formats"
		]
		!immutable [
			"uuid"
			"type"
		]
		!deprecated [
			"preload_count"
		]
		unique "instance"
	}

	#
	# Default attributes for steamaudio
	#
	uuid			$STEAMAUDIO_UUID
	type			"effect"
	no_pm			"true"
	cpc			$STEAMAUDIO_CPC
	is_pages		1
	num_input_pins		2
	num_output_pins		1
}
