#
# A TFLM Classification component for SOF. All attributes defined herein are namespaced
# by alsatplg to "Object.Widget.tflmcly.attribute_name"
#

Class.Widget."tflmcly" {
	#
	# Pipeline ID
	#
	DefineAttribute."index" {
		type "integer"
	}

	#
	# Unique instance for TFLM widget
	#
	DefineAttribute."instance" {
		type "integer"
	}

	# Include common widget attributes definition
	<include/components/widget-common.conf>

	attributes {
		!constructor [
			"index"
			"instance"
		]
		!mandatory [
			"num_input_pins"
			"num_output_pins"
			"num_input_audio_formats"
			"num_output_audio_formats"
		]

		!immutable [
			"uuid"
		]
		!deprecated [
			"preload_count"
		]
		unique	"instance"
	}

	#
	# Default attributes for tflmcly
	# UUID: c51dc642-a2e1-48df-a490e2748cb6363e
	#
	uuid			"42:c6:1d:c5:e1:a2:df:48:a4:90:e2:74:8c:b6:36:3e"
	type			"effect"
	no_pm			"true"
	num_input_pins		1
	num_output_pins		1
}
