// SPDX-License-Identifier: BSD-3-Clause
// Auto-generated by sof_tflm_train.py — do not edit.

#ifndef G_SOF_TFLM_QUANTIZED_MODEL_DATA_H_
#define G_SOF_TFLM_QUANTIZED_MODEL_DATA_H_

#include <cstddef>
#include <cstdint>

extern const unsigned char g_sof_tflm_quantized_model_data[];
extern const size_t g_sof_tflm_quantized_model_data_size;

#endif  // G_SOF_TFLM_QUANTIZED_MODEL_DATA_H_
