define(DEF_TDFB_PRIV, concat(`tdfb_priv_', PIPELINE_ID))
define(DEF_TDFB_BYTES, concat(`tdfb_bytes_', PIPELINE_ID))
define(DEF_TDFB_BEAM, concat(`tdfb_beam_', PIPELINE_ID))
define(DEF_TDFB_DIRECTION, concat(`tdfb_track_', PIPELINE_ID))
define(DEF_TDFB_AZIMUTH, concat(`tdfb_az_set_', PIPELINE_ID))
define(DEF_TDFB_AZIMUTH_ESTIMATE, concat(`tdfb_az_est_', PIPELINE_ID))
define(DEF_TDFB_AZIMUTH_VALUES, concat(`tdfb_azimuth_values_', PIPELINE_ID))
