#ifndef LOAD_TYPE
#define LOAD_TYPE "0"
#endif

	REM # smart amp test module config
	[[module.entry]]
	name = "SMATEST"
	uuid = UUIDREG_STR_SMART_AMP_TEST
	affinity_mask = "0x1"
	instance_count = "1"
	domain_types = "0"
	load_type = LOAD_TYPE
	init_config = "1"
	module_type = "0xD"
	auto_start = "0"
	sched_caps = [1, 0x00008000]

	REM # pin = [dir, type, sample rate, size, container, channel-cfg]
	pin = [0, 0, 0xfeef, 0xf, 0xa, 0x45ff,
			0, 0, 0xfeef, 0xf, 0xa, 0x45ff,
			1, 0, 0xfeef, 0xf, 0xa, 0x45ff]

	REM # mod_cfg [PAR_0 PAR_1 PAR_2 PAR_3 IS_BYTES CPS IBS OBS MOD_FLAGS CPC OBLS]
#ifdef CONFIG_METEORLAKE
	mod_cfg = [0, 0, 0, 0, 296, 5000000, 384, 384, 0, 5000, 0]
#elif defined(CONFIG_LUNARLAKE) || defined(CONFIG_SOC_INTEL_ACE30)
	mod_cfg = [0, 0, 0, 0, 4096, 1000000, 128, 128, 0, 0, 0]
#endif

	index = __COUNTER__
