# SOF west manifest
manifest:
  version: "0.13"

  defaults:
    remote: thesofproject

  remotes:
    - name: thesofproject
      url-base: https://github.com/thesofproject
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: rimage
      repo-path: rimage
      path: sof/rimage
      revision: 02abc5d342a3ee6965bdc933ea1439d85d0256da

    - name: tomlc99
      repo-path: tomlc99
      path: sof/rimage/tomlc99
      revision: e3a03f5ec7d8d33be705c5ce8a632d998ce9b4d1

      # west update will override your local changes to this revision
    - name: zephyr
      repo-path: zephyr
      revision: 63a497280f22aea39793dd9de9731469a83ce533
      remote: zephyrproject
      import:
        name-whitelist:
          - hal_xtensa
          - mbedtls
          - mipi-sys-t
          - lz4
          - tinycrypt

  self:
    path: sof
    import: submanifests
