/* SRC constants */
#define MAX_FIR_DELAY_SIZE 592
#define MAX_OUT_DELAY_SIZE 577
#define MAX_BLK_IN 25
#define MAX_BLK_OUT 25
#define NUM_IN_FS 6
#define NUM_OUT_FS 6
#define STAGE1_TIMES_MAX 21
#define STAGE2_TIMES_MAX 25
#define STAGE_BUF_SIZE 168
#define NUM_ALL_COEFFICIENTS 2184
