/* SRC constants */
#define MAX_FIR_DELAY_SIZE 698
#define MAX_OUT_DELAY_SIZE 900
#define MAX_BLK_IN 80
#define MAX_BLK_OUT 40
#define NUM_IN_FS 15
#define NUM_OUT_FS 10
#define STAGE1_TIMES_MAX 21
#define STAGE2_TIMES_MAX 32
#define STAGE_BUF_SIZE 224
#define NUM_ALL_COEFFICIENTS 20076
