				# All input formats for e.g. host-copier
				num_input_audio_formats 20
				CombineArrays.Object.Base.input_audio_format [
					{
						in_rate [
							8000
							44100
							48000
							96000
							192000
						]
						in_bit_depth [ 8 ]
						in_valid_bit_depth [ 8 ]
						in_sample_type [ $SAMPLE_TYPE_UNSIGNED_INTEGER ]
					}
					{
						in_rate [
							8000
							44100
							48000
							96000
							192000
						]
						in_bit_depth [ 16 ]
						in_valid_bit_depth [ 16 ]
					}
					{
						in_rate [
							8000
							44100
							48000
							96000
							192000
						]
						in_bit_depth [ 32 ]
						in_valid_bit_depth [ 24 ]
					}
					{
						in_rate [
							8000
							44100
							48000
							96000
							192000
						]
						in_bit_depth [ 32 ]
						in_valid_bit_depth [ 32 ]
					}
				]
