				# Input formats for e.g. micsel
				num_input_audio_formats 10
				CombineArrays.Object.Base.input_audio_format [
					{
						in_channels [ 1 ]
						in_rate [
							8000
							44100
							48000
							96000
							192000
						]
						in_bit_depth [ 32 ]
						in_valid_bit_depth [ 32 ]
						in_ch_map [ $CHANNEL_MAP_MONO ]
						in_ch_cfg [ $CHANNEL_CONFIG_MONO ]
					}
					{
						in_rate [
							8000
							44100
							48000
							96000
							192000
						]
						in_bit_depth [ 32 ]
						in_valid_bit_depth [ 32 ]
					}
				]
