				# Output audio formats e.g. module-copier
				num_output_audio_formats 10
				CombineArrays.Object.Base.output_audio_format [
					{
						out_channels [ 1 ]
						out_rate [
							8000
							44100
							48000
							96000
							192000
						]
						out_bit_depth [ 32 ]
						out_valid_bit_depth [ 32 ]
						out_ch_map [ $CHANNEL_MAP_MONO ]
						out_ch_cfg [ $CHANNEL_CONFIG_MONO ]
					}
					{
						out_rate [
							8000
							44100
							48000
							96000
							192000
						]
						out_bit_depth [ 32 ]
						out_valid_bit_depth [ 32 ]
					}
				]
