# Xtensa CMake toolchain file. Apply it using CMAKE_TOOLCHAIN_FILE variable.

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_VERSION 1)

cmake_path(CONVERT $ENV{XTENSA_TOOLCHAIN_PATH} TO_CMAKE_PATH_LIST XTENSA_TOOLCHAIN_PATH)
set(TOOLCHAIN_BASE ${XTENSA_TOOLCHAIN_PATH}/XtensaTools)
set(CROSS_COMPILE ${TOOLCHAIN_BASE}/bin/xt-)

# clang or xcc
find_program(CMAKE_C_COMPILER NAMES ${CROSS_COMPILE}xcc NO_DEFAULT_PATH)
# clang++ or xc++
find_program(CMAKE_CXX_COMPILER NAMES ${CROSS_COMPILE}xc++ NO_DEFAULT_PATH)

find_program(CMAKE_LD NAMES ${CROSS_COMPILE}ld NO_DEFAULT_PATH)
find_program(CMAKE_AR NAMES ${CROSS_COMPILE}ar NO_DEFAULT_PATH)
find_program(CMAKE_RANLIB NAMES ${CROSS_COMPILE}ranlib NO_DEFAULT_PATH)
find_program(CMAKE_OBJCOPY NAMES ${CROSS_COMPILE}objcopy NO_DEFAULT_PATH)
find_program(CMAKE_OBJDUMP NAMES ${CROSS_COMPILE}objdump NO_DEFAULT_PATH)
find_program(CMAKE_NM NAMES ${CROSS_COMPILE}nm NO_DEFAULT_PATH)

set(CMAKE_FIND_ROOT_PATH ${TOOLCHAIN_BASE}/xtensa-elf)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
