// SPDX-License-Identifier: BSD-3-Clause
//
// Copyright(c) 2021 Intel Corporation. All rights reserved.

#ifndef _ADSP__LOG_TRANSPORT_H
#define _ADSP__LOG_TRANSPORT_H

#include <stdint.h>
#include <stdbool.h>

typedef struct log_transport log_transport_s;

typedef enum trigger_transport_event
{
    EVENT_BUFFER_HALF_FULL,
    EVENT_BUFFER_FULL,
    EVENT_TIMER,
    EVENT_NEW_ENTRY_ADDED
} trigger_transport_event_e;

#define NO_DEFINED_LOG_FORMAT 0xFFFFFFFF

struct log_transport
{
    /**
     * @brief Called when transport should transmit log data.
     *
     * @param [in] transport log_transport pointer
     * @param [in] event trigger_transport_event_e event triggering transmit log data request
     */
    void (*trigger_transport_)(log_transport_s const* transport, trigger_transport_event_e event);

    /**
     * @brief Called on transport init
     *
     * @param [in] transport log_transport pointer
     * @param [in] read_ptr pointer to read position, which should be updated accordingly after each buffer is sent
     * @param [in] write_ptr pointer to write position
     * @param [in] buffer_start pointer to buffer containing log data
     * @param [in] buffer_size buffer size
     */
    void (*init_)(log_transport_s const* transport, uint32_t* read_ptr, uint32_t* write_ptr, uint8_t* buffer_start, uint32_t buffer_size);

    /**
     * @brief Called during transport detaching. After this call transport becomes unusable.
     * */
    void (*release_)(log_transport_s const* transport);

    /**
     * @brief Determines whether transport can work with buffer memory in DCACHE. Set to false if it cannot.
     * */
    bool buffer_cacheable_;

    /**
     * @brief Determines whether transport wants to be triggered every time new log entry is added.
     * */
    bool trigger_on_new_entry_;

    /**
     * @brief Determines number of bits required by transport to be left-shifted in timestamps generated by logger.
     * */
    uint32_t timestamp_shift_;
    /**
     * @brief Determines id of log format required by this transport, or NO_DEFINED_LOG_FORMAT if it's not crucial.
     * */
    uint32_t defined_log_format_;
};

#endif
