# default settings for Compressed Audio Playback
Define {
	COMPRESSED		false
	COMPR_DEEPBUFFER_MS	100 # 100 ms copier dma size

	COMPRESSED_1		true
	COMPR_PCM_NAME		'Compress Playback'
	COMPR_PCM_ID		50
	COMPR_PIPELINE_ID	90


	COMPRESSED_2		false
	COMPR_2_PCM_NAME	'Compress Playback 2'
	COMPR_2_PCM_ID		52
	COMPR_2_PIPELINE_ID	92
}
