Define {
	SDW_JACK_ECHO_REF_PCM_ID 11
	SDW_JACK_ECHO_REF_PIPELINE_ID 12
}

IncludeByKey.SDW_JACK_ECHO_REF {
	"true" {
		Object.Pipeline {
			siggen-host-copier-capture [
				{
					direction "capture"
					index $SDW_JACK_ECHO_REF_PIPELINE_ID
					Object.Widget.host-copier."1" {
						stream_name "Jack Echo Reference"
						pcm_id $SDW_JACK_ECHO_REF_PCM_ID
						num_input_audio_formats 1
						Object.Base.input_audio_format [
							{
								in_rate			$JACK_RATE
								in_bit_depth		32
								in_valid_bit_depth	32
							}
						]
						num_output_audio_formats 3
						Object.Base.output_audio_format [
							{
								out_rate		$JACK_RATE
								out_bit_depth		16
								out_valid_bit_depth	16
							}
							{
								out_rate		$JACK_RATE
								out_bit_depth		32
								out_valid_bit_depth	24
							}
							{
								out_rate		$JACK_RATE
								out_bit_depth		32
								out_valid_bit_depth	32
							}
						]
					}
					Object.Widget.siggen."1" {
						num_input_pins 1
						num_output_pins 1
						num_input_audio_formats 1
						num_output_audio_formats 1
						Object.Base.input_audio_format [
							{
								in_rate			$JACK_RATE
								in_bit_depth		32
								in_valid_bit_depth	32
							}
						]
						Object.Base.output_audio_format [
							{
								out_rate		$JACK_RATE
								out_bit_depth		32
								out_valid_bit_depth	32
							}
						]
					}
				}
			]
		}

		Object.PCM.pcm [
			{
				name	    "Jack Echo Reference"
				id	    $SDW_JACK_ECHO_REF_PCM_ID
				direction   "capture"
				Object.Base.fe_dai.1 {
					    name	"Jack Echo Reference"
				}
				Object.PCM.pcm_caps.1 {
					name "Jack Echo Reference"
					formats 'S16_LE,S24_LE,S32_LE'
				}
				IncludeByKey.JACK_RATE {
					"48000" {
						rates '48000'
					}
					"96000" {
						rates '96000'
					}
					"192000" {
						rates '192000'
					}
				}
			}
		]

		Object.Base.route [
			{
				source "alh-copier.Loopback_Virtual.25"
				sink "siggen.$SDW_JACK_ECHO_REF_PIPELINE_ID.1"
			}
			{
				source "module-copier.1.12"
				sink   "siggen.$SDW_JACK_ECHO_REF_PIPELINE_ID.1"
			}
			{
				source "siggen.$SDW_JACK_ECHO_REF_PIPELINE_ID.1"
				sink "host-copier.$SDW_JACK_ECHO_REF_PCM_ID.capture"
			}
		]
	} # SDW_JACK_ECHO_REF true
}
