Define {
	SDW_SPK_ECHO_REF_PCM_ID 12
	SDW_SPK_ECHO_REF_PIPELINE_ID 120
}

IncludeByKey.SDW_SPK_ECHO_REF {
	"true" {
		Object.Pipeline {
			siggen-host-copier-capture [
				{
					direction "capture"
					index $SDW_SPK_ECHO_REF_PIPELINE_ID
					Object.Widget.host-copier."1" {
						stream_name "Speaker Echo Reference"
						pcm_id $SDW_SPK_ECHO_REF_PCM_ID
					}
					Object.Widget.siggen."1" {}
				}
			]
		}

		Object.PCM.pcm [
			{
				name	    "Speaker Echo Reference"
				id	    $SDW_SPK_ECHO_REF_PCM_ID
				direction   "capture"
				Object.Base.fe_dai.1 {
					    name	"Speaker Echo Reference"
				}
				Object.PCM.pcm_caps.1 {
					name "Speaker Echo Reference"
					formats 'S16_LE,S24_LE,S32_LE'
				}
			}
		]

		Object.Base.route [
			{
				source "alh-copier.Loopback_Virtual.25"
				sink "siggen.$SDW_SPK_ECHO_REF_PIPELINE_ID.1"
			}
			{
				source "module-copier.21.22"
				sink   "siggen.$SDW_SPK_ECHO_REF_PIPELINE_ID.1"
			}
			{
				source "siggen.$SDW_SPK_ECHO_REF_PIPELINE_ID.1"
				sink "host-copier.$SDW_SPK_ECHO_REF_PCM_ID.capture"
			}
		]
	} # SDW_SPK_ECHO_REF true
}
