Define {
	SDW_JACK_MODULE_COPIER_ID 11
	SDW_JACK_AUDIO_FEATURE_CAPTURE_PCM_NAME "Jack In Audio Features"
	SDW_JACK_AUDIO_FEATURE_CAPTURE_PCM_ID 47
	SDW_JACK_AUDIO_FEATURE_CAPTURE_STREAM_NAME "Jack In Audio Features Stream"
	SDW_JACK_AUDIO_FEATURE_CAPTURE_PIPELINE_ID 130
}

Object.Pipeline.host-gateway-src-mfcc-capture [
	{
		index $SDW_JACK_AUDIO_FEATURE_CAPTURE_PIPELINE_ID

		Object.Widget.host-copier.1 {
			stream_name "$SDW_JACK_AUDIO_FEATURE_CAPTURE_STREAM_NAME"
			pcm_id $SDW_JACK_AUDIO_FEATURE_CAPTURE_PCM_ID
		}

		Object.Widget.mfcc.1 {
			Object.Control {
				bytes."1" {
					name "$SDW_JACK_AUDIO_FEATURE_CAPTURE_PCM_NAME MFCC bytes"
					<include/components/mfcc/mel80.conf>
				}
			}
		}
	}
]
Object.Base.route [
	{
		source "module-copier.$SDW_JACK_MODULE_COPIER_ID.0"
		sink "src.$SDW_JACK_AUDIO_FEATURE_CAPTURE_PIPELINE_ID.1"
	}
	{
		source "mfcc.$SDW_JACK_AUDIO_FEATURE_CAPTURE_PIPELINE_ID.1"
		sink "host-copier.$SDW_JACK_AUDIO_FEATURE_CAPTURE_PCM_ID.capture"
	}
]

Object.PCM.pcm [
	{
		name "$SDW_JACK_AUDIO_FEATURE_CAPTURE_PCM_NAME"
		id $SDW_JACK_AUDIO_FEATURE_CAPTURE_PCM_ID
		direction "capture"
		Object.Base.fe_dai.1 {
			name "$SDW_JACK_AUDIO_FEATURE_CAPTURE_PCM_NAME"
		}

		Object.PCM.pcm_caps.1 {
			name "$SDW_JACK_AUDIO_FEATURE_CAPTURE_STREAM_NAME"
			formats 'S32_LE'
			rates '16000'
			channels_min $SDW_JACK_CAPTURE_CH
			channels_max $SDW_JACK_CAPTURE_CH
		}
	}
]
