# Use this overlay to increase log verbosity for
# all runtime heap allocs.
#
# Logs (LOG_INF) are emitted from all heap types (system heap 'sof_heap',
# virtual heap allocator, vregions, ...)
#

CONFIG_SYS_HEAP_RUNTIME_STATS=y
CONFIG_SYS_MEM_BLOCKS_RUNTIME_STATS=y
