# SPDX-License-Identifier: BSD-3-Clause
# Auto-generated: newlib libm sources COMPILED into libnewlib_m.a.
# The 13 common/*.c that are only textually #included by these are present
# in the tree but deliberately excluded here (compiling them standalone
# would multiply-define exp/log/pow/...). See README. Do not edit by hand;
# regenerate with the recipe in README.
set(NEWLIB_MATH_SOURCES
  common/copysignl.c
  common/exp10l.c
  common/exp_data.c
  common/fabsl.c
  common/frexpl.c
  common/log2_data.c
  common/log_data.c
  common/math_denorm.c
  common/math_denormf.c
  common/math_denorml.c
  common/math_err_check_oflow.c
  common/math_err_check_uflow.c
  common/math_err_divzero.c
  common/math_err_invalid.c
  common/math_err_may_uflow.c
  common/math_err_oflow.c
  common/math_err_uflow.c
  common/math_err_with_errno.c
  common/math_errf_check_oflowf.c
  common/math_errf_check_uflowf.c
  common/math_errf_divzerof.c
  common/math_errf_invalidf.c
  common/math_errf_may_uflowf.c
  common/math_errf_oflowf.c
  common/math_errf_uflowf.c
  common/math_errf_with_errnof.c
  common/math_inexact.c
  common/math_inexactf.c
  common/math_inexactl.c
  common/nanl.c
  common/nexttoward.c
  common/nexttowardf.c
  common/pow_log_data.c
  common/s_cbrt.c
  common/s_copysign.c
  common/s_exp10.c
  common/s_expm1.c
  common/s_fdim.c
  common/s_finite.c
  common/s_fma.c
  common/s_fmax.c
  common/s_fmin.c
  common/s_fpclassify.c
  common/s_getpayload.c
  common/s_ilogb.c
  common/s_infinity.c
  common/s_iseqsig.c
  common/s_isinf.c
  common/s_isnan.c
  common/s_issignaling.c
  common/s_llrint.c
  common/s_llround.c
  common/s_log1p.c
  common/s_log2.c
  common/s_logb.c
  common/s_lrint.c
  common/s_lround.c
  common/s_modf.c
  common/s_nan.c
  common/s_nearbyint.c
  common/s_nextafter.c
  common/s_pow10.c
  common/s_remquo.c
  common/s_rint.c
  common/s_round.c
  common/s_scalbln.c
  common/s_scalbn.c
  common/s_signbit.c
  common/s_trunc.c
  common/sf_cbrt.c
  common/sf_copysign.c
  common/sf_exp10.c
  common/sf_exp2_data.c
  common/sf_expm1.c
  common/sf_fdim.c
  common/sf_finite.c
  common/sf_fma.c
  common/sf_fmax.c
  common/sf_fmin.c
  common/sf_fpclassify.c
  common/sf_getpayload.c
  common/sf_ilogb.c
  common/sf_infinity.c
  common/sf_iseqsig.c
  common/sf_isinf.c
  common/sf_isnan.c
  common/sf_issignaling.c
  common/sf_llrint.c
  common/sf_llround.c
  common/sf_log1p.c
  common/sf_log2_data.c
  common/sf_log_data.c
  common/sf_logb.c
  common/sf_lrint.c
  common/sf_lround.c
  common/sf_modf.c
  common/sf_nan.c
  common/sf_nearbyint.c
  common/sf_nextafter.c
  common/sf_pow10.c
  common/sf_pow_log2_data.c
  common/sf_remquo.c
  common/sf_rint.c
  common/sf_round.c
  common/sf_scalbln.c
  common/sf_scalbn.c
  common/sf_trunc.c
  common/signgam.c
  common/sincosf_data.c
  common/sl_iseqsig.c
  common/sl_issignaling.c
  math/k_cos.c
  math/k_rem_pio2.c
  math/k_sin.c
  math/k_tan.c
  math/kf_cos.c
  math/kf_rem_pio2.c
  math/kf_sin.c
  math/kf_tan.c
  math/s_acos.c
  math/s_acosh.c
  math/s_asin.c
  math/s_asinh.c
  math/s_atan.c
  math/s_atan2.c
  math/s_atanh.c
  math/s_ceil.c
  math/s_cos.c
  math/s_cosh.c
  math/s_drem.c
  math/s_erf.c
  math/s_exp.c
  math/s_exp2.c
  math/s_fabs.c
  math/s_floor.c
  math/s_fmod.c
  math/s_frexp.c
  math/s_hypot.c
  math/s_j0.c
  math/s_j1.c
  math/s_jn.c
  math/s_lgamma.c
  math/s_log.c
  math/s_log10.c
  math/s_pow.c
  math/s_rem_pio2.c
  math/s_remainder.c
  math/s_scalb.c
  math/s_signif.c
  math/s_sin.c
  math/s_sincos.c
  math/s_sinh.c
  math/s_sqrt.c
  math/s_tan.c
  math/s_tanh.c
  math/s_tgamma.c
  math/sf_acos.c
  math/sf_acosh.c
  math/sf_asin.c
  math/sf_asinh.c
  math/sf_atan.c
  math/sf_atan2.c
  math/sf_atanh.c
  math/sf_ceil.c
  math/sf_cos.c
  math/sf_cosh.c
  math/sf_drem.c
  math/sf_erf.c
  math/sf_exp.c
  math/sf_exp2.c
  math/sf_fabs.c
  math/sf_floor.c
  math/sf_fmod.c
  math/sf_frexp.c
  math/sf_hypot.c
  math/sf_j0.c
  math/sf_j1.c
  math/sf_jn.c
  math/sf_lgamma.c
  math/sf_log.c
  math/sf_log10.c
  math/sf_log2.c
  math/sf_pow.c
  math/sf_rem_pio2.c
  math/sf_remainder.c
  math/sf_scalb.c
  math/sf_signif.c
  math/sf_sin.c
  math/sf_sincos.c
  math/sf_sinh.c
  math/sf_sqrt.c
  math/sf_tan.c
  math/sf_tanh.c
  math/sf_tgamma.c
  math/sl_hypot.c
  math/sr_lgamma.c
  math/srf_lgamma.c
)
