define(DEF_TDFB_PRIV, concat(`tdfb_priv_', PIPELINE_ID))
define(DEF_TDFB_BYTES, concat(`tdfb_bytes_', PIPELINE_ID))
define(DEF_TDFB_ONOFF_ENUM, concat(`tdfb_onoff_enum_', PIPELINE_ID))
define(DEF_TDFB_DIRECTION_ENUM, concat(`tdfb_direction_enum_', PIPELINE_ID))
define(DEF_TDFB_ONOFF, concat(`tdfb_onoff_', PIPELINE_ID))
define(DEF_TDFB_BEAMN, concat(`tdfb_beamn_', PIPELINE_ID))
