		# Created with script "bench_comp_generate.sh ffmpeg_dec"
		Object.Base.route [
			{
				sink '$BENCH_PLAYBACK_DAI_COPIER'
				source 'ffmpeg_dec.$BENCH_PLAYBACK_HOST_PIPELINE.1'
			}
			{
				sink 'ffmpeg_dec.$BENCH_PLAYBACK_HOST_PIPELINE.1'
				source 'host-copier.0.playback'
			}
			{
				source '$BENCH_CAPTURE_DAI_COPIER'
				sink 'ffmpeg_dec.$BENCH_CAPTURE_HOST_PIPELINE.2'
			}
			{
				source 'ffmpeg_dec.$BENCH_CAPTURE_HOST_PIPELINE.2'
				sink 'host-copier.0.capture'
			}
		]
