		# Created with script "bench_comp_generate.sh ffmpeg_dec"
		Object.Widget.ffmpeg_dec.1 {
			index $BENCH_PLAYBACK_HOST_PIPELINE
			<include/bench/one_input_output_format_s24.conf>
			<include/bench/ffmpeg_dec_controls_playback.conf>
		}
		Object.Widget.ffmpeg_dec.2 {
			index $BENCH_CAPTURE_HOST_PIPELINE
			<include/bench/one_input_output_format_s24.conf>
			<include/bench/ffmpeg_dec_controls_capture.conf>
		}
		<include/bench/host_gateway_pipelines_s24.conf>
		<include/bench/ffmpeg_dec_route.conf>
