			# Created initially with script "bench_comp_generate.sh ffmpeg_dec"
			# may need edits to modify controls
			Object.Control {
				# Un-comment the supported controls in FFMPEG_DEC
				#bytes."1" {
				#	name '$ANALOG_PLAYBACK_PCM FFMPEG_DEC bytes'
				#	IncludeByKey.BENCH_FFMPEG_DEC_PARAMS {
				#		"default" "include/components/ffmpeg_dec/default.conf"
				#	}
				#}
				#mixer."1" {
				#	name '$ANALOG_PLAYBACK_PCM FFMPEG_DEC switch or volume'
				#}
				#enum."1" {
				#	name '$ANALOG_PLAYBACK_PCM FFMPEG_DEC enum'
				#}
			}
