			# Created initially with script "./bench_comp_generate.sh mfcc"
			# may need edits to modify controls
			Object.Control {
				# Un-comment the supported controls in MFCC
				bytes."1" {
					name '$ANALOG_CAPTURE_PCM MFCC bytes'
					IncludeByKey.BENCH_MFCC_PARAMS {
						"default" "include/components/mfcc/default.conf"
						"mel80" "include/components/mfcc/mel80.conf"
					}
				}
				#mixer."1" {
				#	name '$ANALOG_CAPTURE_PCM MFCC switch or volume'
				#}
				#enum."1" {
				#	name '$ANALOG_CAPTURE_PCM MFCC enum'
				#}
			}
