		# Created with script "./bench_comp_generate.sh mfcc"
		Object.Widget.mfcc.1 {
			index $BENCH_PLAYBACK_HOST_PIPELINE
			<include/bench/one_input_output_format_s16_16k.conf>
			<include/bench/mfcc_controls_playback.conf>
		}
		Object.Widget.mfcc.2 {
			index $BENCH_CAPTURE_HOST_PIPELINE
			<include/bench/one_input_output_format_s16_16k.conf>
			<include/bench/mfcc_controls_capture.conf>
		}
		<include/bench/host_gateway_pipelines_s16_16k.conf>
		<include/bench/mfcc_route.conf>
