			# Created initially with script "./bench_comp_generate.sh sound_dose"
			# may need edits to modify controls
			Object.Control {
				# Un-comment the supported controls in SOUND_DOSE
				bytes."1" {
					name '$ANALOG_CAPTURE_PCM SOUND_DOSE bytes'
					IncludeByKey.BENCH_SOUND_DOSE_PARAMS {
						"default" "include/components/sound_dose/setup_sens_100db.conf"
					}
				}
				#mixer."1" {
				#	name '$ANALOG_CAPTURE_PCM SOUND_DOSE switch or volume'
				#}
				#enum."1" {
				#	name '$ANALOG_CAPTURE_PCM SOUND_DOSE enum'
				#}
			}
