% ref_pcan - Generate C header files for PCAN library unit tests
%
% SPDX-License-Identifier: BSD-3-Clause
% Copyright(c) 2026 Intel Corporation. All rights reserved.

function ref_pcan()
	% Add path to cmocka helper export functions
	path(path(), '../../../m');

	try
		opt.describe = export_get_git_describe();
	catch
		opt.describe = 'SOF PCAN Reference Generator';
	end

	%% Phase 1: Export Golden LUTs for default and custom configurations
	export_ref_lut(opt);

	%% Phase 2 & 3: Export Golden values for WideDynamicFunction and PcanShrink
	export_ref_functions(opt);

	%% Phase 4: Export Streaming Multi-Channel Multi-Frame Test Vectors
	export_ref_streaming(opt);

	%% Phase 5: Export Corner & Edge Cases
	export_ref_corner_cases(opt);

	fprintf(1, 'All PCAN test headers exported successfully.\n');
end

function export_ref_lut(opt)
	header_fn = 'ref_pcan_lut.h';
	fh = export_headerfile_open(header_fn);
	export_comment(fh, sprintf('Generated by ref_pcan.m (%s)', opt.describe));

	% Config 1: Default TFLM configuration
	cfg1.strength = 0.95;
	cfg1.offset = 80.0;
	cfg1.gain_bits = 21;
	input_bits1 = 10;
	[lut1, ~] = pcan_gain_lookup(cfg1, input_bits1);

	export_ndefine(fh, 'PCAN_TEST_LUT1_SIZE', length(lut1));
	export_ndefine(fh, 'PCAN_TEST_LUT1_GAIN_BITS', cfg1.gain_bits);
	export_ndefine(fh, 'PCAN_TEST_LUT1_INPUT_BITS', input_bits1);
	export_vector(fh, 16, 'ref_pcan_lut1', lut1);

	% Config 2: Custom configuration (strength=0.8, offset=50.0, gain_bits=18)
	cfg2.strength = 0.8;
	cfg2.offset = 50.0;
	cfg2.gain_bits = 18;
	input_bits2 = 12;
	[lut2, ~] = pcan_gain_lookup(cfg2, input_bits2);

	export_ndefine(fh, 'PCAN_TEST_LUT2_SIZE', length(lut2));
	export_ndefine(fh, 'PCAN_TEST_LUT2_GAIN_BITS', cfg2.gain_bits);
	export_ndefine(fh, 'PCAN_TEST_LUT2_INPUT_BITS', input_bits2);
	export_vector(fh, 16, 'ref_pcan_lut2', lut2);

	fclose(fh);
	fprintf(1, 'Exported %s.\n', header_fn);
end

function export_ref_functions(opt)
	header_fn = 'ref_pcan_func.h';
	fh = export_headerfile_open(header_fn);
	export_comment(fh, sprintf('Generated by ref_pcan.m (%s)', opt.describe));

	cfg.strength = 0.95;
	cfg.offset = 80.0;
	cfg.gain_bits = 21;
	input_bits = 10;
	[lut, ~] = pcan_gain_lookup(cfg, input_bits);

	% 1. WideDynamicFunction Test Vector: Test various points across all 32 intervals
	wdf_inputs = uint32([ ...
		0, 1, 2, 3, 4, 5, 7, 8, 15, 16, 31, 32, 63, 64, 127, 128, ...
		255, 256, 511, 512, 1023, 1024, 2047, 2048, 4095, 4096, 8191, 8192, ...
		16383, 16384, 32767, 32768, 65535, 65536, 131071, 131072, ...
		262143, 262144, 524287, 524288, 1048575, 1048576, 2097151, 2097152, ...
		4194303, 4194304, 8388607, 8388608, 16777215, 16777216, ...
		33554431, 33554432, 67108863, 67108864, 134217727, 134217728, ...
		268435455, 268435456, 536870911, 536870912, 1073741823, 1073741824, ...
		2147483647, 2147483648, 4294967295 ...
	]);
	wdf_outputs = pcan_wide_dynamic_func(wdf_inputs, lut);

	export_ndefine(fh, 'PCAN_TEST_WDF_NUM_POINTS', length(wdf_inputs));
	export_uint32_vector(fh, 'ref_pcan_wdf_inputs', wdf_inputs);
	export_vector(fh, 16, 'ref_pcan_wdf_outputs', wdf_outputs);

	% 2. PcanShrink Test Vector: Sweep below, around (8192), and above threshold
	shrink_inputs = uint32([ ...
		0, 1, 10, 100, 500, 1000, 2000, 4000, 8000, 8190, 8191, 8192, 8193, 8194, ...
		10000, 16384, 32768, 65536, 100000, 500000, 1000000, 10000000 ...
	]);
	shrink_outputs = pcan_shrink(shrink_inputs, 12, 6);

	export_ndefine(fh, 'PCAN_TEST_SHRINK_NUM_POINTS', length(shrink_inputs));
	export_uint32_vector(fh, 'ref_pcan_shrink_inputs', shrink_inputs);
	export_uint32_vector(fh, 'ref_pcan_shrink_outputs', shrink_outputs);

	fclose(fh);
	fprintf(1, 'Exported %s.\n', header_fn);
end

function export_ref_streaming(opt)
	header_fn = 'ref_pcan_stream.h';
	fh = export_headerfile_open(header_fn);
	export_comment(fh, sprintf('Generated by ref_pcan.m (%s)', opt.describe));

	cfg.strength = 0.95;
	cfg.offset = 80.0;
	cfg.gain_bits = 21;
	cfg.smoothing_coef = 819; % 0.05 in Q14
	smoothing_bits = 10;
	input_correction_bits = 0;

	num_channels = 16;
	num_frames = 20;

	% Create deterministic synthetic test signal:
	% Baseline background noise + mid-stream bursts
	rng(42);
	input_matrix = zeros(num_channels, num_frames, 'uint32');
	for f = 1:num_frames
		for c = 1:num_channels
			noise = 50 + mod(c * 17 + f * 23, 100);
			if f >= 5 && f <= 12 && c >= 4 && c <= 10
				speech_burst = 2000 + (c * 150);
			else
				speech_burst = 0;
			end
			input_matrix(c, f) = uint32(noise + speech_burst);
		end
	end

	[output_matrix, final_noise] = pcan_process(input_matrix, cfg, smoothing_bits, input_correction_bits);

	export_ndefine(fh, 'PCAN_STREAM_NUM_CHANNELS', num_channels);
	export_ndefine(fh, 'PCAN_STREAM_NUM_FRAMES', num_frames);
	export_ndefine(fh, 'PCAN_STREAM_SMOOTHING_COEF', cfg.smoothing_coef);
	export_ndefine(fh, 'PCAN_STREAM_SMOOTHING_BITS', smoothing_bits);
	export_ndefine(fh, 'PCAN_STREAM_INPUT_CORRECTION_BITS', input_correction_bits);

	input_linear = reshape(input_matrix, [], 1);
	output_linear = reshape(output_matrix, [], 1);

	export_uint32_vector(fh, 'ref_pcan_stream_inputs', input_linear);
	export_uint32_vector(fh, 'ref_pcan_stream_outputs', output_linear);
	export_uint32_vector(fh, 'ref_pcan_stream_final_noise', final_noise);

	fclose(fh);
	fprintf(1, 'Exported %s.\n', header_fn);
end

function export_ref_corner_cases(opt)
	header_fn = 'ref_pcan_corners.h';
	fh = export_headerfile_open(header_fn);
	export_comment(fh, sprintf('Generated by ref_pcan.m (%s)', opt.describe));

	cfg.strength = 0.95;
	cfg.offset = 80.0;
	cfg.gain_bits = 21;
	input_bits = 10;
	[lut, ~] = pcan_gain_lookup(cfg, input_bits);

	% Corner case points: zeros, boundaries, transitions, overflows
	corner_inputs = uint32([ ...
		0, ...
		1, ...
		2, ...
		3, ...
		4, ...
		2047, 2048, 2049, ...
		8191, 8192, 8193, ...
		65535, 65536, 65537, ...
		1073741823, 1073741824, 1073741825, ...
		2147483647, 2147483648, 2147483649, ...
		4294967294, 4294967295 ...
	]);

	wdf_corner_outs = pcan_wide_dynamic_func(corner_inputs, lut);
	shrink_corner_outs = pcan_shrink(corner_inputs, 12, 6);

	export_ndefine(fh, 'PCAN_CORNERS_NUM_POINTS', length(corner_inputs));
	export_uint32_vector(fh, 'ref_pcan_corner_inputs', corner_inputs);
	export_vector(fh, 16, 'ref_pcan_corner_wdf_outputs', wdf_corner_outs);
	export_uint32_vector(fh, 'ref_pcan_corner_shrink_outputs', shrink_corner_outs);

	fclose(fh);
	fprintf(1, 'Exported %s.\n', header_fn);
end

function export_uint32_vector(fh, vname, data)
	columns = 6;
	rows = ceil(length(data) / columns);
	fprintf(fh, '\nstatic const uint32_t %s[%d] = {\n', vname, length(data));
	i = 1;
	for j = 1:rows
		fprintf(fh, '\t%11uU,', data(i));
		i = i + 1;
		for k = 2:columns
			if i <= length(data)
				fprintf(fh, ' %11uU,', data(i));
				i = i + 1;
			end
		end
		fprintf(fh, '\n');
	end
	fprintf(fh, '};\n');
end
