/* SPDX-License-Identifier: BSD-3-Clause
 *
 * Copyright(c) 2026 Intel Corporation.
 */

/* Generated by ref_pcan.m (v1.9-rc1-7901-g9500fa321) */

#define PCAN_CORNERS_NUM_POINTS  22

static const uint32_t ref_pcan_corner_inputs[22] = {
	          0U,           1U,           2U,           3U,           4U,        2047U,
	       2048U,        2049U,        8191U,        8192U,        8193U,       65535U,
	      65536U,       65537U,  1073741823U,  1073741824U,  1073741825U,  2147483647U,
	 2147483648U,  2147483649U,  4294967294U,  4294967295U,
};

static const int16_t ref_pcan_corner_wdf_outputs[22] = {
	 32636,  32635,  32635,  32635,  32634,  31879,  31879,  31879,  29812,  29811,
	 29811,  18676,  18672,  18672,      4,      4,      4,      2,      2,      2,
	     1,      1,
};

static const uint32_t ref_pcan_corner_shrink_outputs[22] = {
	          0U,           0U,           0U,           0U,           0U,           3U,
	          4U,           4U,          63U,          64U,          64U,         959U,
	        960U,         960U,    16777151U,    16777152U,    16777152U,    33554367U,
	   33554368U,    33554368U,    67108799U,    67108799U,
};
