// SPDX-License-Identifier: BSD-3-Clause
/*
 * Copyright (c) 2026 Sound Open Firmware (SOF) Project
 */

#include <rtos/sof.h>
#include <rtos/clk.h>
#include <platform/lib/clk.h>
#include <sof/lib/dma.h>
#include <sof/lib/dai.h>
#include <sof/schedule/edf_schedule.h>
#include <sof/schedule/ll_schedule.h>
#include <sof/schedule/ll_schedule_domain.h>
#include <sof/lib/mailbox.h>
#include <sof/fw-ready-metadata.h>
#include <sof_versions.h>
#include <kernel/abi.h>
#include <sof/debug/debug.h>
#include <zephyr/logging/log.h>
#include <fsl_clock.h>
#include <fsl_iomuxc.h>

LOG_MODULE_REGISTER(teensy41_platform, CONFIG_SOF_LOG_LEVEL);

uint8_t sof_teensy_mailbox[0x1000] __aligned(32);

static const struct sof_ipc_fw_ready ready = {
	.hdr = {
		.cmd = SOF_IPC_FW_READY,
		.size = sizeof(struct sof_ipc_fw_ready),
	},
	.version = {
		.hdr.size = sizeof(struct sof_ipc_fw_version),
		.micro = SOF_MICRO,
		.minor = SOF_MINOR,
		.major = SOF_MAJOR,
		.build = -1,
		.date = "dtermin.\0",
		.time = "fwready.\0",
		.tag = SOF_TAG,
		.abi_version = SOF_ABI_VERSION,
		.src_hash = SOF_SRC_HASH,
	},
	.flags = DEBUG_SET_FW_READY_FLAGS,
};

static const struct sof_ipc_window windows = {
	.ext_hdr = {
		.hdr.cmd = SOF_IPC_FW_READY,
		.hdr.size = sizeof(struct sof_ipc_window),
		.type = SOF_IPC_EXT_WINDOW,
	},
	.num_windows = 3,
	.window = {
		{
			.type = SOF_IPC_REGION_DOWNBOX,
			.flags = 0,
			.size = MAILBOX_HOSTBOX_SIZE,
			.offset = MAILBOX_HOSTBOX_OFFSET,
		},
		{
			.type = SOF_IPC_REGION_UPBOX,
			.id = 0,
			.flags = 0,
			.size = MAILBOX_DSPBOX_SIZE,
			.offset = MAILBOX_DSPBOX_OFFSET,
		},
		{
			.type = SOF_IPC_REGION_STREAM,
			.id = 0,
			.flags = 0,
			.size = MAILBOX_STREAM_SIZE,
			.offset = MAILBOX_STREAM_OFFSET,
		},
	},
};

int platform_boot_complete(uint32_t boot_message)
{
	struct sof_ipc_reply reply;

	reply.error = 0;
	reply.hdr.cmd = SOF_IPC_FW_READY;
	reply.hdr.size = sizeof(reply);

	mailbox_hostbox_write(0, &reply, sizeof(reply));
	mailbox_hostbox_write(sizeof(reply), &ready, sizeof(ready));
	mailbox_hostbox_write(sizeof(reply) + sizeof(ready),
			      &windows,
			      sizeof(windows));

	LOG_INF("Teensy 4.1 platform boot complete");
	return 0;
}

int platform_context_save(struct sof *sof)
{
	return 0;
}

#include <sof/ipc/common.h>
#include <sof/ipc/schedule.h>
#include <sof/ipc/msg.h>
#include <sof/lib/uuid.h>

SOF_DEFINE_REG_UUID(zipc_task);
extern struct task_ops ipc_task_ops;

int platform_ipc_init(struct ipc *ipc)
{
	ipc_set_drvdata(ipc, NULL);
	schedule_task_init_edf(&ipc->ipc_task, SOF_UUID(zipc_task_uuid),
			       &ipc_task_ops, ipc, 0, 0);
	return 0;
}

enum task_state ipc_platform_do_cmd(struct ipc *ipc)
{
	struct ipc_cmd_hdr *hdr = mailbox_validate();

	if (hdr)
		ipc_cmd(hdr);
	return SOF_TASK_STATE_COMPLETED;
}

int ipc_platform_send_msg(const struct ipc_msg *msg)
{
	mailbox_dspbox_write(0, msg->tx_data, msg->tx_size);
	return 0;
}

static void teensy41_audio_hardware_init(void)
{
	/* 1. Configure Audio PLL (PLL4) for 688.128 MHz:
	 * Fref = 24 MHz, loopDivider = 28, numerator = 6720, denominator = 10000, postDivider = 1
	 * Fpll = 24 * (28 + 6720 / 10000) = 688.128 MHz
	 */
	const clock_audio_pll_config_t audio_pll_cfg = {
		.loopDivider = 28,
		.postDivider = 1,
		.numerator = 6720,
		.denominator = 10000,
		.src = 0, /* 24MHz OSC */
	};
	CLOCK_InitAudioPll(&audio_pll_cfg);

	/* 2. Configure SAI1 clock root: Mux = Audio PLL (2), PreDiv = /4 (3), Podf = /14 (13)
	 * SAI1 MCLK = 688.128 MHz / 4 / 14 = 12.288 MHz (256 * 48000 Hz)
	 */
	CLOCK_SetMux(kCLOCK_Sai1Mux, 2);
	CLOCK_SetDiv(kCLOCK_Sai1PreDiv, 3);
	CLOCK_SetDiv(kCLOCK_Sai1Div, 13);
	CLOCK_EnableClock(kCLOCK_Sai1);

	/* 3. Configure S/PDIF clock root and clock gate */
	CLOCK_EnableClock(kCLOCK_Spdif);

	/* 4. Configure SAI1 I/O Pins and Daisy Chains */
#if defined(CONFIG_TEENSY41_BOARD_B)
	/* Board B: Slave Rx - consumes BCLK and SYNC generated by Board A */
	/* Pin 21: SAI1_RX_BCLK (Input), Daisy Chain 0x401F8590 = 1 */
	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_11_SAI1_RX_BCLK, 1U);
	IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_11_SAI1_RX_BCLK, 0x10B0);

	/* Pin 20: SAI1_RX_SYNC (Input), Daisy Chain 0x401F85A4 = 1 */
	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_10_SAI1_RX_SYNC, 1U);
	IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_10_SAI1_RX_SYNC, 0x10B0);
#else
	/* Board A: Master Tx - drives BCLK and SYNC on Pin 21 and Pin 20 */
	/* Enable MCLK output on Pin 23 (GPIO_AD_B1_09) */
	IOMUXC_GPR->GPR1 |= IOMUXC_GPR_GPR1_SAI1_MCLK_DIR_MASK;
	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_09_SAI1_MCLK, 1U);
	IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_09_SAI1_MCLK, 0x10B0);

	/* Pin 21: SAI1_RX_BCLK with SION=1 (so TX BCLK output feeds back into RX) */
	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_11_SAI1_RX_BCLK, 1U);
	IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_11_SAI1_RX_BCLK, 0x10B0);

	/* Pin 20: SAI1_RX_SYNC with SION=1 (so TX SYNC output feeds back into RX) */
	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_10_SAI1_RX_SYNC, 1U);
	IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_10_SAI1_RX_SYNC, 0x10B0);
#endif

	/* Pin 8: SAI1_RX_DATA0 (Input on GPIO_B1_00), Daisy Chain 0x401F8594 = 2 */
	IOMUXC_SetPinMux(IOMUXC_GPIO_B1_00_SAI1_RX_DATA00, 1U);
	IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_00_SAI1_RX_DATA00, 0x10B0);

	/* Pin 7: SAI1_TX_DATA0 (Output on GPIO_B1_01) */
	IOMUXC_SetPinMux(IOMUXC_GPIO_B1_01_SAI1_TX_DATA00, 0U);
	IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_01_SAI1_TX_DATA00, 0x10B0);

	/* Pin 9: SAI1_TX_DATA2 (Output on GPIO_B0_11) */
	IOMUXC_SetPinMux(IOMUXC_GPIO_B0_11_SAI1_TX_DATA02, 0U);
	IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_11_SAI1_TX_DATA02, 0x10B0);

	/* 5. Configure S/PDIF Pins (Pin 14 = SPDIF_OUT, Pin 15 = SPDIF_IN) */
	/* Pin 14: SPDIF_OUT on GPIO_AD_B1_02 */
	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_02_SPDIF_OUT, 0U);
	IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_02_SPDIF_OUT, 0x10B0);

	/* Pin 15: SPDIF_IN on GPIO_AD_B1_03, Daisy Chain 0x401F85C8 = 0 */
	IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_03_SPDIF_IN, 1U);
	IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_03_SPDIF_IN, 0x10B0);

	/* Explicitly ensure daisy chain select input registers */
	*((volatile uint32_t *)0x401F8590) = 1; /* SAI1_RX_BCLK (GPIO_AD_B1_11) */
	*((volatile uint32_t *)0x401F85A4) = 1; /* SAI1_RX_SYNC (GPIO_AD_B1_10) */
	*((volatile uint32_t *)0x401F8594) = 2; /* SAI1_RX_DATA0 (GPIO_B1_00) */
	*((volatile uint32_t *)0x401F859C) = 1; /* SAI1_TX_DATA2 (GPIO_B0_11) */
	*((volatile uint32_t *)0x401F85C8) = 0; /* SPDIF_IN (GPIO_AD_B1_03) */

	LOG_INF("Teensy 4.1 Audio HW initialized: AudioPLL=688.128MHz, MCLK=12.288MHz, Master=%d",
		!IS_ENABLED(CONFIG_TEENSY41_BOARD_B));
}

int platform_init(struct sof *sof)
{
	LOG_INF("Initializing Teensy 4.1 SOF Platform...");

	platform_clock_init(sof);

	teensy41_audio_hardware_init();

	/* Initialize EDF scheduler */
	scheduler_init_edf();

	/* Initialize Zephyr domain and timer-based LL scheduler */
	sof->platform_timer_domain = zephyr_domain_init(PLATFORM_DEFAULT_CLOCK);
	if (!sof->platform_timer_domain) {
		LOG_ERR("Failed to initialize platform timer domain");
		return -ENODEV;
	}

	zephyr_ll_scheduler_init(sof->platform_timer_domain);

	/* Initialize platform DMAC */
	dmac_init(sof);

	/* Initialize Zephyr native DAI subsystem */
	dai_init(sof);

	/* Initialize IPC */
	ipc_init(sof);

	LOG_INF("Teensy 4.1 SOF Platform initialized successfully");
	return 0;
}

void ipc_platform_complete_cmd(struct ipc *ipc)
{
	ARG_UNUSED(ipc);
}
