/*
 * Copyright (c) 2017-2018, Intel Corporation
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in the
 *     documentation and/or other materials provided with the distribution.
 *   * Neither the name of the Intel Corporation nor the
 *     names of its contributors may be used to endorse or promote products
 *     derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef __INCLUDE_DW_INTC_H__
#define __INCLUDE_DW_INTC_H__

/* platform interrupt control */
#define SUE_DW_ICTL_BASE_ADDR			0x00081800

#define SUE_DW_ICTL_IRQ_INTEN_L			(0x00 + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_IRQ_INTEN_H			(0x04 + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_IRQ_INTMASK_L		(0x08 + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_IRQ_INTMASK_H		(0x0C + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_IRQ_INTFORCE_L		(0x10 + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_IRQ_INTFORCE_H		(0x14 + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_IRQ_RAWSTATUS_L		(0x18 + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_IRQ_RAWSTATUS_H		(0x1C + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_IRQ_STATUS_L		(0x20 + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_IRQ_STATUS_H		(0x24 + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_IRQ_MASKSTATUS_L		(0x28 + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_IRQ_MASKSTATUS_H		(0x2C + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_IRQ_FINALSTATUS_L		(0x30 + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_IRQ_FINALSTATUS_H		(0x34 + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_IRQ_VECTOR			(0x38 + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_IRQ_VECTOR_0		(0x40 + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_IRQ_VECTOR_1		(0x48 + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_IRQ_VECTOR_2		(0x50 + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_IRQ_VECTOR_3		(0x58 + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_IRQ_VECTOR_4		(0x60 + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_IRQ_VECTOR_5		(0x68 + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_IRQ_VECTOR_6		(0x70 + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_IRQ_VECTOR_7		(0x78 + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_IRQ_VECTOR_8		(0x80 + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_IRQ_VECTOR_9		(0x88 + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_IRQ_VECTOR_10		(0x90 + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_IRQ_VECTOR_11		(0x98 + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_IRQ_VECTOR_12		(0xA0 + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_IRQ_VECTOR_13		(0xA8 + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_IRQ_VECTOR_14		(0xB0 + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_IRQ_VECTOR_15		(0xB8 + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_IRQ_FIQ_INTEN		(0xC0 + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_IRQ_FIQ_INTMASK		(0xC4 + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_IRQ_FIQ_INTFORCE		(0xC8 + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_IRQ_FIQ_RAWSTATUS		(0xCC + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_IRQ_FIQ_STATUS		(0xD0 + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_IRQ_FIQ_FINALSTATUS		(0xD4 + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_IRQ_FIQ_PLEVEL		(0xD8 + SUE_DW_ICTL_BASE_ADDR)
#define SUE_DW_ICTL_PR_N(x)			(0xE8 + x*4 + SUE_DW_ICTL_BASE_ADDR)

int dw_intc_irq_init(void);

#endif
