/* SRC constants */
#define MAX_FIR_DELAY_SIZE 415
#define MAX_OUT_DELAY_SIZE 401
#define MAX_BLK_IN 21
#define MAX_BLK_OUT 21
#define NUM_IN_FS 6
#define NUM_OUT_FS 6
#define STAGE1_TIMES_MAX 21
#define STAGE2_TIMES_MAX 21
#define STAGE_BUF_SIZE 168
#define NUM_ALL_COEFFICIENTS 1320
