CONFIG_PANTHERLAKE=y
CONFIG_IPC_MAJOR_4=y

# turn off SOF drivers
CONFIG_CORE_COUNT=5

CONFIG_ZTEST=y
CONFIG_SOF_BOOT_TEST_STANDALONE=y
CONFIG_TEST_USERSPACE=y
CONFIG_MM_DRV=y
CONFIG_ZEPHYR_NATIVE_DRIVERS=y
CONFIG_SOF_USERSPACE_LL=y

CONFIG_COMP_SRC=y

CONFIG_COMP_SRC_IPC4_FULL_MATRIX=y

# power settings
CONFIG_PM=n

# enable Zephyr drivers
CONFIG_DAI_INIT_PRIORITY=70
CONFIG_DAI_DMIC_HW_IOCLK=19200000
CONFIG_DAI_DMIC_HAS_OWNERSHIP=n
CONFIG_DAI_DMIC_HAS_MULTIPLE_LINE_SYNC=y
CONFIG_DAI_INTEL_SSP=n
CONFIG_DMA_INTEL_ADSP_GPDMA=n
CONFIG_DMA_DW_LLI_POOL_SIZE=50
CONFIG_INTEL_MODULES=n
CONFIG_LIBRARY_MANAGER=n

CONFIG_HEAP_MEM_POOL_SIZE=8192
CONFIG_RIMAGE_SIGNING_SCHEMA="ptl"

CONFIG_FORMAT_CONVERT_HIFI3=n
CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=n
CONFIG_LOG_FUNC_NAME_PREFIX_INF=n
CONFIG_SYS_CLOCK_TICKS_PER_SEC=12000
CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC=19200000

CONFIG_LOG_BACKEND_ADSP_MTRACE=n
CONFIG_SOF_LOG_LEVEL_INF=y
CONFIG_SOF_LOG_LEVEL_OFF=n
CONFIG_ZEPHYR_LOG=y

CONFIG_INTEL_ADSP_IPC=y


# Temporary disabled options
CONFIG_PM_DEVICE_RUNTIME=n
CONFIG_PM_DEVICE_POWER_DOMAIN=n
CONFIG_PM_PREWAKEUP_CONV_MODE_CEIL=y
CONFIG_COMP_KPB=n

CONFIG_USERSPACE=y
CONFIG_MAX_THREAD_BYTES=4

CONFIG_COMP_UP_DOWN_MIXER=y
CONFIG_COMP_MODULE_ADAPTER=y
CONFIG_PASSTHROUGH_CODEC=y
CONFIG_COMP_ARIA=y
CONFIG_COMP_MFCC=y
CONFIG_COMP_CROSSOVER=y
CONFIG_COMP_DCBLOCK=y
CONFIG_COMP_IIR=y
CONFIG_COMP_DRC=y
CONFIG_COMP_MULTIBAND_DRC=y
CONFIG_COMP_LEVEL_MULTIPLIER=y
CONFIG_COMP_RTNR=y
CONFIG_COMP_RTNR_STUB=y
CONFIG_COMP_SMART_AMP=y
CONFIG_COMP_TDFB=y
CONFIG_COMP_STFT_PROCESS=y
CONFIG_COMP_GOOGLE_RTC_AUDIO_PROCESSING=y
CONFIG_GOOGLE_RTC_AUDIO_PROCESSING_MOCK=y
CONFIG_COMP_GOOGLE_CTC_AUDIO_PROCESSING=y
CONFIG_GOOGLE_CTC_AUDIO_PROCESSING_MOCK=y
CONFIG_COMP_IGO_NR=y
CONFIG_COMP_IGO_NR_STUB=y
CONFIG_COMP_NXP_EAP=y
CONFIG_COMP_NXP_EAP_STUB=y
CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_COMP_SOUND_DOSE=y
