/* SPDX-License-Identifier: BSD-3-Clause
 *
 * Copyright(c) 2026 Intel Corporation.
 *
 * EQ FIR passthrough config for 2 channels
 * Auto-generated by gen_ztest_blobs.m - do not edit.
 */

#ifndef ZTEST_BLOB_EQ_FIR_BLOB_H
#define ZTEST_BLOB_EQ_FIR_BLOB_H

#include <stdint.h>

static const uint32_t eq_fir_blob[22] = {
	0x34464f53, 0x00000000, 0x00000038, 0x0301d001,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000038, 0x00010002, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0xffff0004,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00004000, 0x00000000
};

#endif /* ZTEST_BLOB_EQ_FIR_BLOB_H */
