version = [1, 0]  # parse_adsp_config_v1_0()

[adsp]
name = "mt8188"

[[adsp.mem_zone]]
type = "IRAM"
base = "0x4e100000"
size = "0x00080000"
host_offset = "0x0"
[[adsp.mem_zone]]
type = "SRAM"
base = "0x60000000"
size = "0x00600000"
host_offset = "0x0"
