version = [1, 0]  # use simple file write

[adsp]
name = "mt8196"

[[adsp.mem_zone]]
type = "IRAM"
base = "0x4e100000"
size = "0x00080000"
host_offset = "0x0"
[[adsp.mem_zone]]
type = "SRAM"
base = "0x90000000"
size = "0x00600000"
host_offset = "0x0"
