version = [1, 5]

[adsp]
name = "sue"
image_size = "0x300000"        # (47 + 1) bank * 64KB
exec_boot_ldr = 1
alias_mask = "0xE0000000"

[[adsp.mem_zone]]
type = "ROM"
base = "0xBEFE0000"
size = "0x00002000"
[[adsp.mem_zone]]
type = "IMR"
base = "0xb0038000"
size = "0x100000"
[[adsp.mem_zone]]
type = "SRAM"
base = "0xbe000000"
size = "0x100000"

[[adsp.mem_alias]]
type = "uncached"
base = "0x9E000000"
[[adsp.mem_alias]]
type = "cached"
base = "0xBE000000"

[fw_desc.header]
name = "ADSPFW"
load_offset = "0x2000"
