version = [1, 0]  # use simple file write

[adsp]
name = "vangogh"

[[adsp.mem_zone]]
type = "IRAM"
base = "0x20000000"
size = "0x40000"
host_offset = "0x0"
[[adsp.mem_zone]]
type = "DRAM"
base = "0xE0000000"
size = "0x100000"
host_offset = "0x0"
