## \struct ipc3_mixer
## \brief IPC3 low-latency mixer widget.

Class.Widget."ipc3-mixer" {
	DefineAttribute."index" {}
	DefineAttribute."instance" {}

	<include/components/widget-common.conf>

	attributes {
		!constructor [
			"index"
			"instance"
		]
		!mandatory [
			"format"
		]
		!immutable [
			"type"
			"uuid"
		]
		unique "instance"
	}

	type	"mixer"
	uuid	"37:c0:06:bc:aa:12:7c:41:9a:97:89:28:2e:32:1a:76"
	no_pm	"true"
}
