#
# BE playback pipeline: mixout-gain-dax-ctc-dai-copier-playback.
#

<include/components/dolby-dax.conf>
<include/components/ctc.conf>
<include/pipelines/cavs/mixout-gain-dai-copier-playback.conf>

Class.Pipeline."mixout-gain-dax-ctc-dai-copier-playback" {
	SubTreeCopy.baseclass {
		# this class extends the mixout-gain-dai-copier-playback class definition
		source "Class.Pipeline.mixout-gain-dai-copier-playback"

		tree {
			Object.Widget {
				dolby-dax."1" {
					num_input_audio_formats 1
					num_output_audio_formats 1
					Object.Base.input_audio_format [
						{
							in_rate			48000
							in_bit_depth		32
							in_valid_bit_depth	32
							ibs			"$[(256 * ($[($in_bit_depth / 8)])) * ($in_channels)]"
						}
					]
					Object.Base.output_audio_format [
						{
							out_rate		48000
							out_bit_depth		32
							out_valid_bit_depth	32
							obs			"$[(256 * ($[($out_bit_depth / 8)])) * ($out_channels)]"
						}
					]
				}

				ctc."1" {
					num_input_audio_formats 1
					num_output_audio_formats 1

					Object.Base.input_audio_format [
						{
							in_rate			48000
							in_bit_depth		32
							in_valid_bit_depth	32
							ibs			"$[(256 * ($[($in_bit_depth / 8)])) * ($in_channels)]"
						}
					]
					Object.Base.output_audio_format [
						{
							out_rate		48000
							out_bit_depth		32
							out_valid_bit_depth	32
							obs			"$[(256 * ($[($out_bit_depth / 8)])) * ($out_channels)]"
						}
					]
				}
			}

			Object.Base {
				! route [
					{
						source gain.$index.1
						sink   dolby-dax.$index.1
					}
					{
						source dolby-dax.$index.1
						sink   ctc.$index.1
					}
				]
			}
		}
	}
}
