Object.Base {
	channel.1 {
		name "fc"
	}
	text.0 {
		name "mww_score_enum_text"
		!values [
			"0%"
			"10%"
			"20%"
			"30%"
			"40%"
			"50%"
			"60%"
			"70%"
			"80%"
			"90%"
			"100%"
		]
	}
	ops.1 {
		name "ctl"
		info "enum"
		get 257
		put 257
	}
}
