# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright (c) 2026 Intel Corporation. All rights reserved.
#
# Steam Audio 64-channel spatial audio & compressed metadata feature topology
#

<searchdir:include>
<searchdir:include/common>
<searchdir:include/components>
<searchdir:include/dais>
<searchdir:include/pipelines>
<searchdir:include/pipelines/cavs>
<searchdir:platform>
<searchdir:platform/intel>

<vendor-token.conf>
<tokens.conf>
<common_definitions.conf>
<host-gateway-playback.conf>
<steamaudio-playback.conf>
<host-copier.conf>
<steamaudio.conf>
<mixin.conf>
<mixout.conf>
<data.conf>
<manifest.conf>
<route.conf>
<pcm.conf>
<pcm_caps.conf>
<fe_dai.conf>

<platform/intel/steamaudio-feature.conf>
