## \struct ipc3_volume_playback
## \brief IPC3 host volume playback pipeline.
##
## IPC3 permits scheduling periods longer than the 1 ms maximum used by IPC4.
## This class keeps that exception local to IPC3 topologies.
##
## (source) host.N.playback -> buffer.N.1 -> volume.N.1 -> buffer.N.2 (sink)

<include/common/route.conf>
<include/components/buffer.conf>
<include/components/host.conf>
<include/components/pipeline.conf>
<include/components/volume.conf>

Class.Pipeline."ipc3-volume-playback" {
	<include/pipelines/ipc3/pipeline-common.conf>

	attributes {
		!constructor [
			"index"
		]
		!mandatory [
			"format"
		]
		!immutable [
			"direction"
		]
		unique	"instance"
	}

	Object.Widget {
		pipeline."1" {}

		host."playback" {
			type		"aif_in"
		}

		buffer."1" {
			periods	2
			caps		"host"
		}

		pga."1" {
			Object.Control.mixer.1 {
				Object.Base.tlv."vtlv_m64s2" {
					Object.Base.scale."m64s2" {}
				}
			}
		}

		buffer."2" {
			periods	2
			caps		"dai"
		}
	}

	Object.Base {
		route."1" {
			source	"host.$index.playback"
			sink	"buffer.$index.1"
		}

		route."2" {
			source	"buffer.$index.1"
			sink	"pga.$index.1"
		}

		route."3" {
			source	"pga.$index.1"
			sink	"buffer.$index.2"
		}
	}

	direction	"playback"
	time_domain	"timer"
	period		1000
	priority	0
	core		0
	frames		0
	mips		5000
}
