#!/bin/bash

rmmod sof_pci_dev
rmmod sof_acpi_dev
rmmod snd_soc_acpi_intel_match
rmmod snd_sof_intel_byt
rmmod snd_sof_intel_hsw
rmmod snd_sof_intel_bdw
rmmod snd_sof_intel_apl
rmmod snd_sof_intel_cnl
rmmod snd_sof_intel_hda_common
rmmod snd_sof

rmmod snd_soc_sst_bytcr_rt5640
rmmod snd_soc_sst_bytcr_rt5651
rmmod snd_soc_sst_cht_bsw_rt5645
rmmod snd_soc_sst_cht_bsw_rt5670
rmmod snd_soc_sst_byt_cht_da7213

rmmod snd_soc_rt5670
rmmod snd_soc_rt5645
rmmod snd_soc_rt5651
rmmod snd_soc_rt5640
rmmod snd_soc_rl6231
rmmod snd_soc_da7213

rmmod snd_soc_acpi
