// SPDX-License-Identifier: BSD-3-Clause
// Auto-generated by sof_mww_train.py — do not edit.

#ifndef MWW_MODEL_DATA_H_
#define MWW_MODEL_DATA_H_

#include <cstddef>
#include <cstdint>

extern const unsigned char mww_model_data[];
extern const size_t mww_model_data_size;

#endif  // MWW_MODEL_DATA_H_
