---
# SPDX-License-Identifier: BSD-3-Clause
# Tools that can save round-trips to github and a lot of time:
#
# yamllint -f parsable this.yml
# pip3 install ruamel.yaml.cmd
# yaml merge-expand this.yml exp.yml && diff -w -u this.yml exp.yml
#
# github.com also has a powerful web editor that can be used without
# committing.

name: codestyle

# yamllint disable-line rule:truthy
on: [pull_request, workflow_call, workflow_dispatch]



jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: 'tree:0'

      - name: run yamllint
        # Quoting to please all parsers is hard. This indirection helps.
        env:
          yamllint_config: '{extends: default, rules: {line-length: {max: 100}}}'
        run: yamllint -f parsable
          -d "$yamllint_config"
          --strict .github/workflows/*.yml *.yml
