---

# https://thesofproject.github.io/latest/developer_guides/unit_tests.html

name: Unit tests

# 'workflow_dispatch' allows running this workflow manually from the
# 'Actions' tab

# yamllint disable-line rule:truthy
on: [pull_request, workflow_dispatch, workflow_call]

permissions:
  contents: read

# Group workflows together to cancel outdated runs, do not cancel manual runs
concurrency:
  group: "${{ github.workflow }}-${{ github.event_name }}-\
          ${{ github.event_name == 'pull_request' && github.ref || github.run_id }}"
  cancel-in-progress: true

jobs:
  cmocka_utests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with: {fetch-depth: 2, filter: 'tree:0'}

      - name: build and run all defconfigs
        run: ./test/test-all-defconfigs.sh
